Header and footer
HaveASeat-Sagra/HaveASeat-frontend pull request #1
Opened 2024-07-08 12:26 UTC by Selerek

2024-07-08 12:27 UTC, amystas commented
zmień nazwy klas "prawy" i "lewy" na angielskie "right" i "left"

2024-07-08 12:29 UTC, Selerek commented
> zmień nazwy klas "prawy" i "lewy" na angielskie "right" i "left"

dzieki mordo jak bede na chacie to zobacze,
zaraz jak na chate mi wyslal????

2024-07-15 08:06 UTC, amystas commented on HaveASeat/src/app/mapa/mapa.component.ts
> +    const cell = room?.cells.find(c => c.positionX === positionX && c.positionY === positionY);
W przyszłości zmień na wybieranie komórek po ich id (masz je w jsonie)

2024-07-18 07:36 UTC, amystas commented on HaveASeat/src/app/mapa/mapa.component.css
> +  z-index: 10;
czemu 10? nie ma innych elementów o atrybucie z-index

2024-07-18 07:53 UTC, amystas requested changes

2024-07-18 07:53 UTC, amystas commented on HaveASeat/src/app/mapa/mapa.component.ts
> +  check(desk :Desk, cell :Cell) :boolean {
nazwa funkcji niejednoznaczna

2024-07-18 07:53 UTC, amystas commented on HaveASeat/src/assets/images/logo.png
projekt w figmie przewiduje inne logo

2024-07-18 07:53 UTC, amystas commented on HaveASeat/src/app/mapa/mapa.component.ts
> +        console.log("prawo")
console.log() możesz zamienić na komentarz w kodzie

2024-07-18 07:53 UTC, amystas commented on HaveASeat/src/app/mapa/mapa.component.ts
> +    }).subscribe(
przestarzałe użycie funkcji, wykorzystaj complete, next i error
dalsze info: https://v17.angular.io/guide/observables#defining-observers

2024-07-18 08:40 UTC, Selerek commented on HaveASeat/src/app/mapa/mapa.component.css
> +  z-index: 10;
nie ma żadnego z indexu tutaj

2024-07-18 08:40 UTC, Selerek commented on HaveASeat/src/app/mapa/mapa.component.ts
> +  check(desk :Desk, cell :Cell) :boolean {
funkcja testowa 123

2024-07-18 08:42 UTC, Selerek commented on HaveASeat/src/assets/images/logo.png
to sie zrobi w innej fazie

2024-07-18 08:42 UTC, Selerek commented on HaveASeat/src/app/mapa/mapa.component.ts
> +        console.log("prawo")
spox

2024-07-18 08:42 UTC, Selerek commented on HaveASeat/src/app/mapa/mapa.component.ts
> +    }).subscribe(
nie ma bata że to zmieniam

2024-07-30 11:15 UTC, merged